@Library('shared-lib') _

pipeline {
    agent any

    stages {
        stage('Run Pipeline') {
            steps {
                script {
                    myPipeline(appName: "App2")
                }
            }
        }
    }
}
